export  {default as Header} from "./Header/Header";
export  {default as Footer} from "./Footer/Footer";
export  {default as Home} from "./Home/Home";
export  {default as LoginPage} from "./Login/LoginPage";
export  {default as SignUp} from "./Signup/SignUp";
export  {default as Option} from "./Option/Option";
export  {default as About} from "./About/About";
export  {default as Contact} from "./Contact/Contact";
export {default as AutoRedirect} from "./Redirect/AutoRedirect"
export {default as Input} from "./Input/Input"
export {default as ExamCardPage} from "./ExamCardPage/ExamCardPage"
export {default as StartExam} from "./QuizCard/StartExam"
export {default as ProtectedRoute} from "./ProtectedRout/ProtectedRoute"
export {default as ResultPage} from "./Result/ResultPage"
export {default as T_Page} from "./TeacherPage/T_Page"
export {default as ViewResult} from "./TeacherPage/ViewResult"
export {default as StudentDetails} from "./TeacherPage/StudentDetails"
export {default as AllStudentlist} from "./TeacherPage/AllStudentList"
export {default as QuestionList} from "./Card/QuestionList"
export {default as AddQuestion} from "./TeacherPage/AddQuestion"
